### ISSUE TITLE
合并Aiwb仓库；修复Inkeys的图标

### ISSUE THREAD

**Issue by dubi906w** [Jursin/Awesome-Class-Softwares#8]
1. Aiwb 仓库目前已经合并到 `Awesome-Iwb/Awesome-Iwb`
2. Inkeys 的图标被错误的用成了这个类似 osu! 的图标：
![image](https://github.com/user-attachments/assets/16b0395f-e4ba-4609-b7fe-ccbc0cbc380a)

**Comment by Jursin** [comment]
> 1. Aiwb 仓库目前已经合并到 `Awesome-Iwb/Awesome-Iwb`
收到
> 2. Inkeys 的图标被错误的用成了这个类似 osu! 的图标：
> ![image](https://github.com/user-attachments/assets/16b0395f-e4ba-4609-b7fe-ccbc0cbc380a)
> 
感谢反馈，这个可能是当时删除InkCanvasForClass板块时出现的问题
