### ISSUE TITLE
移除 Aris-Station/Awesome-Iwb

### ISSUE THREAD

**Issue by dubi906w** [Jursin/Awesome-Class-Softwares#9]
<img width="594" alt="image" src="https://github.com/user-attachments/assets/eedb480c-8eb0-45ad-946e-2613150a4ad6" />

rt

**Comment by Jursin** [comment]
> <img width="594" alt="image" src="https://github.com/user-attachments/assets/eedb480c-8eb0-45ad-946e-2613150a4ad6" />
> 
> rt

OK
